#!/bin/bash

TMP_DIR=/tmp

CRT=$1

CERT_DIR=$( dirname $CRT )
CERT_NAME=$( basename $CRT )
CERT_BASE_NAME=${CERT_NAME%.*} # cut away extension
CERT_EXTENSION=${CERT_NAME##*.} # remember extension


function printUsage() {
	echo "Usage:"
	echo "  create_new_CSR.sh WHAT"
	echo
	echo "Parameters:"
	echo "  WHAT ... CRT (or PEM) file to be newly generated"
}


if [ "$CRT" == "" ] ; then
	printUsage
	exit 1
fi

case $CRT in
	eck-zimmer)
		keyname=eck-zimmer.at
		cn=eck-zimmer.at
		;;
	owncloud)
		keyname=owncloud
		cn=eck-zimmer.at
		;;
	timetracker)
		keyname=timetracker
		cn=eck-zimmer.at
		;;
	reminder)
		keyname=reminder
		cn=eck-zimmer.at
		;;
	test)
		keyname=test
		cn=eck-zimmer.at
		;;
	*)
		echo "ERROR: unknown WHAT"
		echo "Call without parameters for usage help"
		exit 1
esac

keyfile=${TMP_DIR}/${keyname}.key
csrfile=${TMP_DIR}/${keyname}.csr
crtfile=${CERT_DIR}/${keyname}.crt

openssl req -nodes -newkey rsa:2048 -nodes -keyout $keyfile -out $csrfile -subj "/C=AT/ST=Styria/L=Graz/O=Alexander Eck-Zimmer/CN=${cn}"
chmod 600 $keyfile

CSR="$( cat ${csrfile} )"

TEXT="A new CSR has been generated for ${keyname}\n
   key: ${keyfile}\n
   CSR: ${csrfile}\n
\n
To do:\n
  (1) Paste the following CSR to StartSSL Certification Wizard:\n
\n
`cat ${csrfile}`\n
\n
  (2) wait for the certificate to be generated by StartSSL and download it to:\n
      ${crtfile}\n
\n
or:\n
$CSR
\n
  (3) Put keyfile into ${CERT_DIR}:\n
  mv ${keyfile} ${CERT_DIR}/\n
\n
  (4) ensure that the key file is fmode 600\n
\n
  (5) reload Apache config:\n
      service apache2 reload\n
\n
That's it. Check it out in your browser!\n
"

echo -e $TEXT

echo -e $TEXT | mutt -a "${csrfile}" -s "StartSSL: neues Server-Zerti erzeugen fuer ${keyname}. Key und CSR liegen hier: [$TMP_DIR]" -- alex

