#!/bin/bash
#
# creates a new CSR and tells the user what to do as next steps

#APACHE_DIR=/etc/apache2/ssl
TMP_DIR=/tmp
APACHE_DIR=/tmp

WHAT=$1


function printUsage() {
        echo "Usage:"
        echo "  create_new_CSR.sh WHAT"
        echo
        echo "Parameters:"
        echo "  WHAT ... generate cert for what, can be one of:"
        echo "           eck-zimmer, owncloud, timetracker, reminder"
}


if [ "$WHAT" == "" ] ; then
        printUsage
        exit 1
fi

case $WHAT in
        eck-zimmer)
                keyname=eck-zimmer.at
                cn=eck-zimmer.at
                ;;
        owncloud)
                keyname=owncloud
                cn=eck-zimmer.at
                ;;
        timetracker)
                keyname=timetracker
                cn=eck-zimmer.at
                ;;
        reminder)
                keyname=reminder
                cn=eck-zimmer.at
                ;;
        test)
                keyname=test
                cn=eck-zimmer.at
                ;;
        *)
                echo "ERROR: unknown WHAT"
                echo "Call without parameters for usage help"
                exit 1
esac

keyfile=${APACHE_DIR}/${keyname}.key
csrfile=${APACHE_DIR}/${keyname}.csr
crtfile=${APACHE_DIR}/${keyname}.crt

openssl req -nodes -newkey rsa:2048 -nodes -keyout $keyfile -out $csrfile -subj "/C=AT/ST=Styria/L=Graz/O=Alexander Eck-Zimmer/CN=${cn}"
chmod 600 $keyfile

TEXT="A new CSR has been generated for [ ${keyname} ]"
TEXT="$TEXT \n   key: ${keyfile}"
TEXT="$TEXT \n   CSR: ${csrfile}"
TEXT="$TEXT \n"
TEXT="$TEXT \nTo do:"
TEXT="$TEXT \n  * Paste the following CSR to StartSSL Certification Wizard:"
TEXT="$TEXT \n"
TEXT="$TEXT \n`cat ${csrfile}`"
TEXT="$TEXT \n\n  * wait for the certificate to be generated by StartSSL and download it"
TEXT="$TEXT \nand name it:"
TEXT="$TEXT \n\n  CRT: ${crtfile}"
TEXT="$TEXT \n\n  * Put keyfile into ${apache_dir}"
TEXT="$TEXT \n\n  * chmod 600 keyfile"

echo $TEXT | mutt -s "StartSSL: neues Server-Zerti erzeugen fuer ${keyname}. Key/CRT liegt hier: [$APACHE_DIR]" alex
